=== romanchom/tempowe_smieci/iksemele/bin/Debug/komis.xsd
<xsd:schema xmlns:xsd='http://www.w3.org/2001/XMLSchema'
    targetNamespace='http://www.pkck.com'
    xmlns:pkck='http://www.pkck.com'
    elementFormDefault='qualified'>
    <xsd:element name='samochód'>
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name ='dane_ogólne'>
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name='marka' type='xsd:string'/>
                            <xsd:element name='model' type='xsd:string'/>
                            <xsd:element name='kolor' type='xsd:string'/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name='dane_sprzedaży'>
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name='cena' type='xsd:decimal'/>
                            <xsd:element name='na_raty'>
                                <xsd:simpleType>
                                    <xsd:restriction base='xsd:string'>
                                        <xsd:enumeration value='nie'/>
                                        <xsd:enumeration value='tak'/>
                                    </xsd:restriction>
                                </xsd:simpleType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name='dane_techniczne'>
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name='paliwo' minOccurs='1' maxOccurs='unbounded'>
                                <xsd:simpleType>
                                    <xsd:restriction base='xsd:string'>
                                        <xsd:enumeration value='benzyna'/>
                                        <xsd:enumeration value='diesel'/>
                                        <xsd:enumeration value='lpg'/>
                                    </xsd:restriction>
                                </xsd:simpleType>
                            </xsd:element>
                            <xsd:element name='pojemność_silnika' type='xsd:decimal'/>
                            <xsd:element name='typ' type='xsd:string'/>
                            <xsd:element name='rocznik' type='xsd:decimal'/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
            <xsd:attribute name='nr_katalogowy' type='xsd:string'/>
        </xsd:complexType>
    </xsd:element>
    <xsd:element name='Komis'>
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name='authors'>
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name='student' type='xsd:string' minOccurs='0' maxOccurs='unbounded'/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name='dane'>
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name='content'>
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name='personel'>
                                            <xsd:complexType>
                                                <xsd:sequence>
                                                    <xsd:element name='pracownik' minOccurs='0' maxOccurs='unbounded'>
                                                        <xsd:complexType>
                                                            <xsd:sequence>
                                                                <xsd:element name='imie' type='xsd:string'/>
                                                                <xsd:element name='nazwisko' type='xsd:string'/>
                                                            </xsd:sequence>
                                                            <xsd:attribute name='id_pracownika' type='xsd:string'/>
                                                        </xsd:complexType>
                                                    </xsd:element>
                                                </xsd:sequence>
                                            </xsd:complexType>
                                        </xsd:element>
                                        <xsd:element name='stan-aktualne'>
                                            <xsd:complexType>
                                                <xsd:sequence>
                                                    <xsd:element ref='pkck:samochód' minOccurs='0' maxOccurs='unbounded'/>
                                                </xsd:sequence>
                                            </xsd:complexType>
                                        </xsd:element>
                                        <xsd:element name='stan-archiwum'>
                                            <xsd:complexType>
                                                <xsd:sequence>
                                                    <xsd:element ref='pkck:samochód' minOccurs='0' maxOccurs='unbounded'/>
                                                </xsd:sequence>
                                            </xsd:complexType>
                                        </xsd:element>
                                        <xsd:element name='operacje'>
                                            <xsd:complexType>
                                                <xsd:sequence>
                                                    <xsd:element name='wpis' minOccurs='0' maxOccurs='unbounded'>
                                                        <xsd:complexType>
                                                            <xsd:sequence>
                                                                <xsd:element name='data' type='xsd:date'/>
                                                                <xsd:element name='kwota' type='xsd:decimal'/>
                                                                <xsd:element name='uwagi' type='xsd:string'/>
                                                            </xsd:sequence>
                                                            <xsd:attribute name='typ'>
                                                                
                                                            </xsd:attribute>
                                                            <xsd:attribute name='id_pracownika' type='xsd:string'/>
                                                            <xsd:attribute name='nr_katalogowy' type='xsd:string'/>
                                                        </xsd:complexType>
                                                    </xsd:element>
                                                </xsd:sequence>
                                            </xsd:complexType>
                                        </xsd:element>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
        
        <xsd:key name='klucz_pracownika'>
            <xsd:selector xpath='dane/content/personel/pracownik'/>
            <xsd:field xpath='@id_pracownika'/>
        </xsd:key>
        <xsd:key name='klucz_samochodu'>
            <xsd:selector xpath='dane/content/stan-aktualne/samochód|dane/content/stan-archiwum/samochód'/>
            <xsd:field xpath='@nr_katalogowy'/>
        </xsd:key>
        <xsd:keyref name='klucz_pracownika_ref' refer='pkck:klucz_pracownika'>
            <xsd:selector xpath='dane/content/operacje/wpis'/>
            <xsd:field xpath='@id_pracownika'/>
        </xsd:keyref>
        <xsd:keyref name='klucz_samochodu_ref' refer='pkck:klucz_samochodu'>
            <xsd:selector xpath='dane/content/operacje/wpis'/>
            <xsd:field xpath='@nr_katalogowy'/>
        </xsd:keyref>
    </xsd:element>
  
</xsd:schema>

=== romanchom/tempowe_smieci/iksemele/bin/Debug/komis.xml
<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/css" href="komis.css"?>
<Komis
    xmlns='http://www.pkck.com'
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:schemaLocation='http://www.pkck.com komis.xsd'>
	<authors>
		<student>Roman Chomik</student>
		<student>Filip Wróbel</student>
	</authors>
	<dane>
	<content>
	<personel>
		<pracownik id_pracownika="i2">
			<imie>Jan</imie>
			<nazwisko>Kowalski</nazwisko>
		</pracownik>
		<pracownik id_pracownika="i3">
			<imie>Mieczysław</imie>
			<nazwisko>Skowronek</nazwisko>
		</pracownik>
	</personel>
	<stan-aktualne>
		<samochód nr_katalogowy="i532" >
			<dane_ogólne>
				<marka>opel</marka>
				<model>astra1</model>
				<kolor>zielony</kolor>
			</dane_ogólne>
			<dane_sprzedaży>
				<cena>5000</cena>
				<na_raty>nie</na_raty>
			</dane_sprzedaży>
			<dane_techniczne>
				<paliwo>benzyna</paliwo>
				<pojemność_silnika>1.6</pojemność_silnika>
				<typ>sedan</typ>
				<rocznik>1999</rocznik>
			</dane_techniczne>
		</samochód>
		<samochód nr_katalogowy="i533" >
			<dane_ogólne>
				<marka>opel</marka>
				<model>astra2</model>
				<kolor>zielony</kolor>
			</dane_ogólne>
			<dane_sprzedaży>
				<cena>7000</cena>
				<na_raty>tak</na_raty>
				</dane_sprzedaży>
			<dane_techniczne>
				<paliwo>benzyna</paliwo>
				<pojemność_silnika>1.8</pojemność_silnika>
				<typ>sedan</typ>
				<rocznik>1998</rocznik>
			</dane_techniczne>
		</samochód>
		<samochód nr_katalogowy="i534" >
			<dane_ogólne>
				<marka>opel</marka>
				<model>astra2</model>
				<kolor>czerwony</kolor>
			</dane_ogólne>
			<dane_sprzedaży>
				<cena>9000</cena>
				<na_raty>nie</na_raty>
			</dane_sprzedaży>
			<dane_techniczne>
				<paliwo>diesel</paliwo>
				<pojemność_silnika>1.9</pojemność_silnika>
				<typ>komb</typ>
				<rocznik>2002</rocznik>
			</dane_techniczne>
		</samochód>
		<samochód nr_katalogowy="i535" >
			<dane_ogólne>
				<marka>volkswagen</marka>
				<model>golf4</model>
				<kolor>srebrny</kolor>
			</dane_ogólne>
			<dane_sprzedaży>
				<cena>5000</cena>
				<na_raty>nie</na_raty>
			</dane_sprzedaży>
			<dane_techniczne>
				<paliwo>diesel</paliwo>
				<pojemność_silnika>1.6</pojemność_silnika>
				<typ>coupe</typ>
				<rocznik>1998</rocznik>
			</dane_techniczne>
		</samochód>
		<samochód nr_katalogowy="i536">
			<dane_ogólne>
				 <marka>volkswagen</marka>
				<model>golf5</model>
				<kolor>czarny</kolor>
			</dane_ogólne>
			<dane_sprzedaży>
				<cena>11000</cena>
				<na_raty>tak</na_raty>
			</dane_sprzedaży>
			<dane_techniczne>
				<paliwo>benzyna</paliwo>
				<pojemność_silnika>2.0</pojemność_silnika>
				<typ>coupe</typ>
				<rocznik>2001</rocznik>
			</dane_techniczne>
		</samochód>
		<samochód nr_katalogowy="i537" >
			<dane_ogólne>
				<marka>volkswagen</marka>
				<model>passat</model>
				<kolor>bialy</kolor>
			</dane_ogólne>
			<dane_sprzedaży>
				<cena>15000</cena>
				<na_raty>tak</na_raty>
			</dane_sprzedaży>
			<dane_techniczne>
				<paliwo>diesel</paliwo>
				<pojemność_silnika>2.0</pojemność_silnika>
				<typ>komb</typ>
				<rocznik>2002</rocznik>
			</dane_techniczne>
		</samochód>	
		<samochód nr_katalogowy="i538" >
			<dane_ogólne>
				<marka>volkswagen</marka>
				<model>passat</model>
				<kolor>zielony</kolor>
			</dane_ogólne>
			<dane_sprzedaży>
				<cena>17000</cena>
				<na_raty>nie</na_raty>
			</dane_sprzedaży>
			<dane_techniczne>
				<paliwo>diesel</paliwo>
				<pojemność_silnika>2.2</pojemność_silnika>
				<typ>komb</typ>
				<rocznik>2004</rocznik>
			</dane_techniczne>
		</samochód>	
		<samochód nr_katalogowy="i539" >
			<dane_ogólne>
				<marka>volkswagen</marka>
				<model>passat</model>
				<kolor>czerwony</kolor>
			</dane_ogólne>
			<dane_sprzedaży>
				<cena>17000</cena>
				<na_raty>nie</na_raty>
			</dane_sprzedaży>
			<dane_techniczne>
				<paliwo>diesel</paliwo>
				<pojemność_silnika>2.2</pojemność_silnika>
				<typ>komb</typ>
				<rocznik>2003</rocznik>
			</dane_techniczne>
		</samochód>
		<samochód nr_katalogowy="i540" >
			<dane_ogólne>
				<marka>volkswagen</marka>
				<model>polo</model>
				<kolor>zolty</kolor>
			</dane_ogólne>
			<dane_sprzedaży>
				<cena>12000</cena>
				<na_raty>tak</na_raty>
			</dane_sprzedaży>
			<dane_techniczne>
				<paliwo>benzyna</paliwo>
				<pojemność_silnika>1.4</pojemność_silnika>
				<typ>coupe</typ>
				<rocznik>2002</rocznik>
			</dane_techniczne>
		</samochód>
		<samochód nr_katalogowy="i541" >
			<dane_ogólne>
				<marka>volkswagen</marka>
				<model>tiguan</model>
				<kolor>srebrny</kolor>
			</dane_ogólne>
			<dane_sprzedaży>
				<cena>30000</cena>
				<na_raty>nie</na_raty>
			</dane_sprzedaży>
			<dane_techniczne>
				<paliwo>diesel</paliwo>
				<pojemność_silnika>2.6</pojemność_silnika>
				<typ>suv</typ>
				<rocznik>2011</rocznik>
			</dane_techniczne>
		</samochód>
		<samochód nr_katalogowy="i542" >
			<dane_ogólne>
				<marka>volkswagen</marka>
				<model>jetta</model>
				<kolor>srebrny</kolor>
			</dane_ogólne>
			<dane_sprzedaży>
				<cena>22000</cena>
				<na_raty>nie</na_raty>
			</dane_sprzedaży>
			<dane_techniczne>
				<paliwo>diesel</paliwo>
				<pojemność_silnika>2.0</pojemność_silnika>
				<typ>sedan</typ>
				<rocznik>2008</rocznik>
			</dane_techniczne>
		</samochód>
		<samochód nr_katalogowy="i543" >
			<dane_ogólne>
				<marka>fiat</marka>
				<model>panda</model>
				<kolor>czarny</kolor>
			</dane_ogólne>
			<dane_sprzedaży>
				<cena>20000</cena>
				<na_raty>tak</na_raty>
			</dane_sprzedaży>
			<dane_techniczne>
				<paliwo>benzyna</paliwo>
				<pojemność_silnika>1.8</pojemność_silnika>
				<typ>hatchback</typ>
				<rocznik>2010</rocznik>
			</dane_techniczne>
		</samochód>
		<samochód nr_katalogowy="i544" >
			<dane_ogólne>
				<marka>fiat</marka>
				<model>panda</model>
				<kolor>bialy</kolor>
			</dane_ogólne>
			<dane_sprzedaży>
				<cena>25000</cena>
				<na_raty>tak</na_raty>
			</dane_sprzedaży>
			<dane_techniczne>
				<paliwo>diesel</paliwo>
				<pojemność_silnika>2.0</pojemność_silnika>
				<typ>hatchback</typ>
				<rocznik>2012</rocznik>
			</dane_techniczne>
		</samochód>
		<samochód nr_katalogowy="i545" >
			<dane_ogólne>
				<marka>fiat</marka>
				<model>multipla</model>
				<kolor>rozowy</kolor>
			</dane_ogólne>
			<dane_sprzedaży>
				<cena>100</cena>
				<na_raty>tak</na_raty>
			</dane_sprzedaży>
			<dane_techniczne>
				<paliwo>benzyna</paliwo>
				<pojemność_silnika>1.2</pojemność_silnika>
				<typ>hatchback</typ>
				<rocznik>2010</rocznik>
			</dane_techniczne>
		</samochód>
		<samochód nr_katalogowy="i546" >
			<dane_ogólne>
				<marka>fiat</marka>
				<model>punto</model>
				<kolor>niebieski</kolor>
			</dane_ogólne>
			<dane_sprzedaży>
				<cena>10000</cena>
				<na_raty>tak</na_raty>
			</dane_sprzedaży>
			<dane_techniczne>
				<paliwo>benzyna</paliwo>
				<paliwo>lpg</paliwo>
				<pojemność_silnika>1.6</pojemność_silnika>
				<typ>hatchback</typ>
				<rocznik>2006</rocznik>
			</dane_techniczne>
		</samochód>
	</stan-aktualne>
	<stan-archiwum>
		<samochód nr_katalogowy="i530" >
			<dane_ogólne>
				<marka>fiat</marka>
				<model>punto</model>
				<kolor>czerwony</kolor>
			</dane_ogólne>
			<dane_sprzedaży>
				<cena>4500</cena>
				<na_raty>nie</na_raty>
			</dane_sprzedaży>
			<dane_techniczne>
				<paliwo>benzyna</paliwo>
				<pojemność_silnika>1.1</pojemność_silnika>
				<typ>sedan</typ>
				<rocznik>1997</rocznik>
			</dane_techniczne>
		</samochód>
		<samochód nr_katalogowy="i531" >
			<dane_ogólne>
				<marka>volkswagen</marka>
				<model>golf3</model>
				<kolor>zielony</kolor>
			</dane_ogólne>
			<dane_sprzedaży>
				<cena>3400</cena>
				<na_raty>nie</na_raty>
			</dane_sprzedaży>
			<dane_techniczne>
				<paliwo>diesel</paliwo>
				<pojemność_silnika>1.6</pojemność_silnika>
				<typ>sedan</typ>
				<rocznik>1996</rocznik>
			</dane_techniczne>
		</samochód>
	</stan-archiwum>
	<operacje>
		<wpis typ="sprzedaż" id_pracownika="i2" nr_katalogowy="i531" >
			<data>2014-05-23</data>
			<kwota>4500</kwota>
			<uwagi>brak</uwagi>
		</wpis>
		<wpis typ="sprzedaż" id_pracownika="i2" nr_katalogowy="i530" >
			<data>2014-05-25</data>
			<kwota>4500</kwota>
			<uwagi>brak</uwagi>
		</wpis>
	</operacje>
	</content>
	</dane>
</Komis>
